import type {
  HeroAttributes,
  HeroSkills,
  OriginCategory,
  OriginRarity,
} from "./Hero";

export interface OccupationDefinition {
  aptitudes: readonly string[];
  attributeModifiers: Partial<HeroAttributes>;
  category: OriginCategory;
  name: string;
  rarity: OriginRarity;
  selectionWeight: number;
  skillModifiers: Partial<HeroSkills>;
}

export const OCCUPATIONS: readonly OccupationDefinition[] = [
  {
    name: "Farmer",
    category: "Civilian",
    rarity: "Common",
    selectionWeight: 8,
    aptitudes: ["Hard labor", "Plant knowledge", "Field survival"],
    attributeModifiers: { endurance: 2, strength: 1, willpower: 1 },
    skillModifiers: { defense: 1, spear: 1 },
  },
  {
    name: "Nurse",
    category: "Skilled",
    rarity: "Specialized",
    selectionWeight: 4,
    aptitudes: ["Patient care", "Triage", "Calm under pressure"],
    attributeModifiers: { intelligence: 1, willpower: 1 },
    skillModifiers: { medicine: 4 },
  },
  {
    name: "Soldier",
    category: "Military",
    rarity: "Specialized",
    selectionWeight: 4,
    aptitudes: ["Formation discipline", "Weapon familiarity", "Field endurance"],
    attributeModifiers: { endurance: 1, leadership: 1, strength: 1 },
    skillModifiers: { defense: 3, leadership: 1, sword: 3 },
  },
  {
    name: "Student",
    category: "Civilian",
    rarity: "Common",
    selectionWeight: 7,
    aptitudes: ["Fast learner", "Study habits"],
    attributeModifiers: { intelligence: 2 },
    skillModifiers: { leadership: 1, medicine: 1 },
  },
  {
    name: "Mechanic",
    category: "Skilled",
    rarity: "Specialized",
    selectionWeight: 4,
    aptitudes: ["Repair", "Improvisation", "Machine knowledge"],
    attributeModifiers: { intelligence: 1, strength: 1 },
    skillModifiers: { defense: 2 },
  },
  {
    name: "Hunter",
    category: "Wilderness",
    rarity: "Common",
    selectionWeight: 6,
    aptitudes: ["Tracking", "Fieldcraft", "Patient aim"],
    attributeModifiers: { agility: 2, endurance: 1 },
    skillModifiers: { defense: 1, spear: 3 },
  },
  {
    name: "Teacher",
    category: "Skilled",
    rarity: "Specialized",
    selectionWeight: 4,
    aptitudes: ["Instruction", "Organization", "Mentorship"],
    attributeModifiers: { intelligence: 1, leadership: 2 },
    skillModifiers: { leadership: 3, medicine: 1 },
  },
  {
    name: "Fisherman",
    category: "Civilian",
    rarity: "Common",
    selectionWeight: 7,
    aptitudes: ["Weather sense", "Ropework", "Patience"],
    attributeModifiers: { endurance: 2, agility: 1 },
    skillModifiers: { spear: 2 },
  },
  {
    name: "Woodcutter",
    category: "Civilian",
    rarity: "Common",
    selectionWeight: 7,
    aptitudes: ["Hard labor", "Timber knowledge"],
    attributeModifiers: { strength: 2, endurance: 1 },
    skillModifiers: { defense: 1 },
  },
  {
    name: "Miner",
    category: "Civilian",
    rarity: "Common",
    selectionWeight: 7,
    aptitudes: ["Stone sense", "Tunnel awareness", "Hard labor"],
    attributeModifiers: { endurance: 2, willpower: 1 },
    skillModifiers: { defense: 2 },
  },
  {
    name: "Cook",
    category: "Civilian",
    rarity: "Common",
    selectionWeight: 7,
    aptitudes: ["Food preparation", "Resource efficiency", "Morale care"],
    attributeModifiers: { intelligence: 1, willpower: 1 },
    skillModifiers: { medicine: 1 },
  },
  {
    name: "Carpenter",
    category: "Skilled",
    rarity: "Common",
    selectionWeight: 6,
    aptitudes: ["Construction", "Repair", "Material knowledge"],
    attributeModifiers: { strength: 1, intelligence: 1 },
    skillModifiers: { defense: 2 },
  },
  {
    name: "Blacksmith",
    category: "Skilled",
    rarity: "Specialized",
    selectionWeight: 4,
    aptitudes: ["Metalworking", "Weapon appraisal", "Equipment repair"],
    attributeModifiers: { strength: 2, endurance: 1 },
    skillModifiers: { defense: 2, sword: 1 },
  },
  {
    name: "Herbalist",
    category: "Skilled",
    rarity: "Specialized",
    selectionWeight: 4,
    aptitudes: ["Plant knowledge", "Remedies", "Foraging"],
    attributeModifiers: { intelligence: 2 },
    skillModifiers: { medicine: 3 },
  },
  {
    name: "Merchant",
    category: "Civilian",
    rarity: "Common",
    selectionWeight: 5,
    aptitudes: ["Negotiation", "Appraisal", "Logistics"],
    attributeModifiers: { intelligence: 1, leadership: 1 },
    skillModifiers: { leadership: 2 },
  },
  {
    name: "Courier",
    category: "Civilian",
    rarity: "Common",
    selectionWeight: 6,
    aptitudes: ["Route memory", "Fast travel", "Awareness"],
    attributeModifiers: { agility: 2, endurance: 1 },
    skillModifiers: { defense: 1 },
  },
  {
    name: "Engineer",
    category: "Skilled",
    rarity: "Specialized",
    selectionWeight: 3,
    aptitudes: ["Systems thinking", "Construction", "Problem solving"],
    attributeModifiers: { intelligence: 3 },
    skillModifiers: { defense: 2, leadership: 1 },
  },
  {
    name: "Apothecary",
    category: "Skilled",
    rarity: "Specialized",
    selectionWeight: 3,
    aptitudes: ["Remedies", "Toxicology", "Ingredient appraisal"],
    attributeModifiers: { intelligence: 2, willpower: 1 },
    skillModifiers: { medicine: 4 },
  },
  {
    name: "Cartographer",
    category: "Skilled",
    rarity: "Specialized",
    selectionWeight: 3,
    aptitudes: ["Mapmaking", "Navigation", "Spatial memory"],
    attributeModifiers: { intelligence: 2, agility: 1 },
    skillModifiers: { leadership: 1 },
  },
  {
    name: "Thief",
    category: "Underworld",
    rarity: "Common",
    selectionWeight: 4,
    aptitudes: ["Stealth", "Lockwork", "Deception"],
    attributeModifiers: { agility: 3 },
    skillModifiers: { defense: 1, sword: 1 },
  },
  {
    name: "Smuggler",
    category: "Underworld",
    rarity: "Specialized",
    selectionWeight: 3,
    aptitudes: ["Hidden routes", "Deception", "Logistics"],
    attributeModifiers: { agility: 1, intelligence: 1, willpower: 1 },
    skillModifiers: { leadership: 1 },
  },
  {
    name: "Mercenary",
    category: "Underworld",
    rarity: "Specialized",
    selectionWeight: 3,
    aptitudes: ["Threat assessment", "Weapon familiarity", "Independence"],
    attributeModifiers: { strength: 1, agility: 1, willpower: 1 },
    skillModifiers: { defense: 2, sword: 2 },
  },
  {
    name: "Spy",
    category: "Underworld",
    rarity: "Rare",
    selectionWeight: 1,
    aptitudes: ["Observation", "Deception", "Infiltration"],
    attributeModifiers: { agility: 2, intelligence: 2 },
    skillModifiers: { leadership: 1, sword: 1 },
  },
  {
    name: "Guard",
    category: "Military",
    rarity: "Common",
    selectionWeight: 5,
    aptitudes: ["Vigilance", "Formation discipline", "Protection"],
    attributeModifiers: { endurance: 1, strength: 1 },
    skillModifiers: { defense: 3, spear: 2 },
  },
  {
    name: "Scout",
    category: "Military",
    rarity: "Specialized",
    selectionWeight: 3,
    aptitudes: ["Reconnaissance", "Stealth", "Route finding"],
    attributeModifiers: { agility: 2, endurance: 1 },
    skillModifiers: { defense: 1, spear: 2 },
  },
  {
    name: "Archer",
    category: "Military",
    rarity: "Specialized",
    selectionWeight: 3,
    aptitudes: ["Ranged discipline", "Patient aim", "Threat selection"],
    attributeModifiers: { agility: 2, willpower: 1 },
    skillModifiers: { defense: 1 },
  },
  {
    name: "Combat Medic",
    category: "Military",
    rarity: "Rare",
    selectionWeight: 1,
    aptitudes: ["Battlefield triage", "Formation discipline", "Crisis response"],
    attributeModifiers: { intelligence: 2, willpower: 2 },
    skillModifiers: { defense: 2, medicine: 4 },
  },
  {
    name: "Officer",
    category: "Military",
    rarity: "Rare",
    selectionWeight: 1,
    aptitudes: ["Command", "Tactics", "Formation discipline"],
    attributeModifiers: { leadership: 3, willpower: 1 },
    skillModifiers: { defense: 2, leadership: 4, sword: 1 },
  },
  {
    name: "Noble",
    category: "Leadership",
    rarity: "Specialized",
    selectionWeight: 2,
    aptitudes: ["Negotiation", "Administration", "Court etiquette"],
    attributeModifiers: { intelligence: 1, leadership: 2 },
    skillModifiers: { leadership: 3 },
  },
  {
    name: "Diplomat",
    category: "Leadership",
    rarity: "Rare",
    selectionWeight: 1,
    aptitudes: ["Negotiation", "Conflict reading", "Persuasion"],
    attributeModifiers: { intelligence: 2, leadership: 3 },
    skillModifiers: { leadership: 4 },
  },
  {
    name: "Village Chief",
    category: "Leadership",
    rarity: "Specialized",
    selectionWeight: 2,
    aptitudes: ["Administration", "Mediation", "Resource planning"],
    attributeModifiers: { leadership: 3, willpower: 1 },
    skillModifiers: { leadership: 3, medicine: 1 },
  },
  {
    name: "Tracker",
    category: "Wilderness",
    rarity: "Common",
    selectionWeight: 5,
    aptitudes: ["Tracking", "Trail concealment", "Fieldcraft"],
    attributeModifiers: { agility: 2, intelligence: 1 },
    skillModifiers: { spear: 2 },
  },
  {
    name: "Explorer",
    category: "Wilderness",
    rarity: "Specialized",
    selectionWeight: 3,
    aptitudes: ["Navigation", "Adaptability", "Field survival"],
    attributeModifiers: { endurance: 1, intelligence: 1, willpower: 1 },
    skillModifiers: { leadership: 1, spear: 1 },
  },
  {
    name: "Monster Hunter",
    category: "Wilderness",
    rarity: "Rare",
    selectionWeight: 1,
    aptitudes: ["Monster lore", "Tracking", "Threat assessment"],
    attributeModifiers: { agility: 2, endurance: 1, willpower: 2 },
    skillModifiers: { defense: 2, spear: 3, sword: 2 },
  },
  {
    name: "Elite Knight",
    category: "Rare",
    rarity: "Rare",
    selectionWeight: 1,
    aptitudes: ["Advanced swordplay", "Command", "Protection"],
    attributeModifiers: { endurance: 2, leadership: 2, strength: 2 },
    skillModifiers: { defense: 4, leadership: 2, sword: 4 },
  },
  {
    name: "Arcane Scholar",
    category: "Rare",
    rarity: "Rare",
    selectionWeight: 1,
    aptitudes: ["Arcane theory", "Research", "Hidden magical potential"],
    attributeModifiers: { intelligence: 4, willpower: 2 },
    skillModifiers: { medicine: 1 },
  },
  {
    name: "Veteran Commander",
    category: "Rare",
    rarity: "Rare",
    selectionWeight: 1,
    aptitudes: ["Command", "Tactics", "Battlefield judgment"],
    attributeModifiers: { leadership: 4, willpower: 2, endurance: 1 },
    skillModifiers: { defense: 3, leadership: 5, sword: 2 },
  },
] as const;
